Django_Online_Shop/urls.py
from django.contrib import admin
from django.urls import path
# library to add applications
from django.urls import include
# libraries to add static root for whole project
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

# adding primary application - home (index.html) and catalog
urlpatterns += [
    path('', include('catalog.urls'))
]

urlpatterns += [
    path('accounts/', include('accounts.urls'))
]

# adding media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("", views.AccountsRedirect, name="redirect"),
    path("agreement/", views.AgreementView, name="agreement"),
    path("profile/", views.ProfileView, name="profile"),
    path("profile/orders/", views.ProfileOrdersView, name="profile-orders"),
    path("profile/orders/<int:pk>", views.ProfileOrderDetailsView, name="profile-order-details"),
    path("signup/", views.SignUpView, name="signup"),
    path("activate/<slug:uidb64>/<slug:token>", views.activate, name='activate'),
    path("change-email/<slug:uidb64>/<slug:token>", views.change_email, name='change-email'),
    path("login/", views.LoginView, name="login"),
    path("logout/", views.LogoutView, name="logout"),
    path("password-reset/", views.PasswordReset, name="reset"),
    path("password-reset/<slug:uidb64>/<slug:token>", views.PasswordResetConfirm, name='reset-confirm'),
    path("password-change/", views.PasswordChangeView, name="password-change"),
    path("subscribe/", views.Subscribe, name="subscribe"),
    path("subscribe/<slug:uidb64>/<slug:token>", views.subscribe_verification, name='subscribe-verification'),
    path("cart/", views.CartView, name="cart"),
    path("cart/controller/", views.cart_controller, name="cart-controller"),
    path("cart/checkout/", views.CheckoutView, name="checkout"),
]

catalog/urls.py
from django.urls import path

import Django_Online_Shop.settings
from . import views
from . import models

app_name="catalog"

urlpatterns = [
    path('', views.IndexView.as_view(), name='home')
]

if Django_Online_Shop.settings.DEBUG:
    urlpatterns += [path("images/", views.image_transfer, name='images')]
#adding catalog urls
urlpatterns += [
    path("catalog/", views.CarsListView.as_view(), name="catalog")
]

urlpatterns += [
    path("catalog/search/", views.CarsSearchView.as_view(), name="search")
]


urlpatterns += [
    path("catalog/category/<slug:category>/", views.CarsByCategoryListView.as_view(), name="category")
]


urlpatterns += [
    path("car/<slug:slug>/", views.CarDetailView.as_view(), name="car")
]

urlpatterns += [
    path("rate/<int:pk>", views.rate, name="rate")
]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile, Order, Rating


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required', required=True)
    first_name = forms.CharField(max_length=150, help_text='Required', required=True)
    last_name = forms.CharField(max_length=150, help_text='Required', required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def clean(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username):
            self.add_error("username", "Username is already used.")
        if User.objects.filter(email=email).exists():
            self.add_error("email", "Email is already used.")
        return self.cleaned_data


class SignupProfileForm(forms.ModelForm):
    agreement = forms.BooleanField(widget=forms.CheckboxInput(attrs={'style': 'vertical-align: inherit'}),
                                   required=True)

    class Meta:
        model = Profile
        fields = ("address", "city", "country", "phone", "delivery", "agreement", "subscription",)


class SubscribeForm(forms.Form):
    email = forms.EmailField(max_length=200, help_text="Required", required=True)


class UserEditForm(forms.ModelForm):
    username = forms.CharField(max_length=150, help_text='Required', required=True)

    first_name = forms.CharField(max_length=150, help_text='Required', required=True)
    last_name = forms.CharField(max_length=150, help_text='Required', required=True)

    email = forms.EmailField(max_length=200, help_text='Required', required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(
                username=self.instance.username).exists():
            self.add_error("email", "Email is already used")
        return email


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("address", "city", "country", "phone", "delivery", "subscription",)


class CheckoutForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True

    agreement = forms.BooleanField(widget=forms.CheckboxInput(attrs={'style': 'vertical-align: inherit'}),
                                   required=True)
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address', 'city', 'country', 'phone', 'delivery', 'agreement')

accounts/views.py
import datetime

import accounts.urls
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, PasswordChangeForm
from django.contrib.auth.models import User, Group
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from mailchimp_marketing import Client
from mailchimp_marketing.api_client import ApiClientError
from catalog.views import get_previous_and_current_url, NavView
from .forms import SignupForm, SubscribeForm, UserEditForm, SignupProfileForm, ProfileEditForm, CheckoutForm
from .tokens import account_activation_token, subscription_token
from catalog.models import Cars
from collections import OrderedDict
from django.db import transaction
from .models import Order, LineItem
import copy

# Mailchimp Settings
api_key = settings.MAILCHIMP_API_KEY
server = settings.MAILCHIMP_DATA_CENTER
list_id = settings.MAILCHIMP_EMAIL_LIST_ID


# APPLICATION FUNCTIONS
# Subscription Logic
def subscribe(email):
    """
     Contains code handling the communication to the mailchimp api
     to create a contact/member in an audience/list.
    """

    mailchimp = Client()
    mailchimp.set_config({
        "api_key": api_key,
        "server": server,
    })

    member_info = {
        "email_address": email,
        "status": "subscribed",
    }

    try:
        response = mailchimp.lists.add_list_member(list_id, member_info)
        print("MAILCHIMP response: {}".format(response))
    except ApiClientError as error:
        print("MAILCHIMP An exception occurred: {}".format(error.text))
        return error.status_code


def unsubscribe(email):
    """
     Contains code handling the communication to the mailchimp api
     to create a contact/member in an audience/list.
    """

    mailchimp = Client()
    mailchimp.set_config({
        "api_key": api_key,
        "server": server,
    })

    try:
        response = mailchimp.lists.delete_list_member(list_id, email)
        print("MAILCHIMP response: {}".format(response))
    except ApiClientError as error:
        print("MAILCHIMP An exception occurred: {}".format(error.text))
        return error.status_code


def subscribe_send_email(request, user, email):
    mail_subject = 'AUTOY SHOP - Subscription email verification'
    mail_template = 'accounts/subscribe_verification_email.html'
    current_site = get_current_site(request)
    message = render_to_string(mail_template, {
        'user': user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(email)),
        'token': subscription_token.make_token(user),
    })
    to_email = email
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    email.send()


def send_email(request, user, email, email_type, order_details=None):
    if email_type == "activation":
        mail_subject = 'AUTOY SHOP - Activate your account'
        mail_template = 'accounts/activation_email.html'
    elif email_type == "reset":
        mail_subject = 'AUTOY SHOP - Reset your password'
        mail_template = 'accounts/password_reset_email.html'
    elif email_type == "change_email":
        mail_subject = 'AUTOY SHOP - Change email request'
        mail_template = 'accounts/change_email_request_email.html'
    elif email_type == "checkout":
        mail_subject = 'AUTOY SHOP - Order Receipt'
        mail_template = 'accounts/checkout_email.html'
    else:
        raise ValueError("Wrong email type")
    current_site = get_current_site(request)
    if email_type == "checkout":
        message = render_to_string(mail_template, {
            'user': user,
            'domain': current_site.domain,
            'profile': order_details["profile"],
            'cart_total_price': order_details["cart_total_price"],
            'cart': order_details["cart"],
            'order_number': order_details["order_number"],
            'bought_date': order_details["bought_date"],
        })
    else:
        message = render_to_string(mail_template, {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
    to_email = email
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    email.send()


def navbar():
    nav = NavView()
    return nav.get_context_data()


def email_confirm_check(request):
    email_confirm = request.session.get('email_confirm', None)
    context = {"email_confirm": ""}
    if email_confirm:
        context["email_confirm"] = email_confirm
        del request.session['email_confirm']
        request.session.modified = True
    return context


# NO TEMPLATE VIEWS
def AccountsRedirect(request):
    return redirect("accounts:profile")


def subscribe_verification(request, uidb64, token):
    try:
        email = force_str(urlsafe_base64_decode(uidb64))
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        email = None
    if email is not None and subscription_token.check_token("Customer", token):
        response = subscribe(email)
        if response:
            if response == 400:
                request.session["email_confirm"] = {"message": "You are already subscribed", "success": False}
            else:
                return HttpResponse("Some errors encountered. Try again later...")
        else:
            request.session["email_confirm"] = {"message": "You are successfully subscribed", "success": True}
        return redirect("accounts:subscribe")
    else:
        request.session["email_confirm"] = {"message": "Verification link is invalid!", "success": False}
        return redirect("accounts:subscribe")


def change_email(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        unsubscribe(user.email)
        user.email = user.profile.temp_email
        user.profile.temp_email = ""
        user.save()
        request.session["email_confirm"] = {
            "message": "Thank you for your email confirmation. Now your email is changed", "success": True}
        if user.profile.subscription:
            response = subscribe(user.email)
            if response:
                if response != 400:
                    user.profile.subscription = False
                    user.profile.save()
                    request.session["email_confirm"][
                        "message"] += " \nWe had some problems with newslatters subscription. \nResubscribe later..."
        return redirect("accounts:profile")
    else:
        request.session["email_confirm"] = {"message": "Change email link is invalid!", "success": False}
        return redirect("accounts:profile")


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        logout(request)
        request.session["email_confirm"] = {
            "message": "Thank you for your email confirmation. Now you can login your account", "success": True}
        if user.profile.subscription:
            response = subscribe(user.email)
            if response:
                if response != 400:
                    user.profile.subscription = False
                    user.profile.save()
                    request.session["email_confirm"][
                        "message"] += " \nWe had some problems with newslatters subscription. \nResubscribe later..."
        return redirect("accounts:login")
    else:
        request.session["email_confirm"] = {"message": "Activation link is invalid!", "success": False}
        return redirect("accounts:login")


# VIEWS


def AgreementView(request):
    context = navbar()
    return render(request, 'accounts/agreement.html', context=context)


def LoginView(request):
    # get previous and current urls for redirecting
    urls = get_previous_and_current_url(request)
    if request.user.is_authenticated:
        return redirect(urls["previous_full_url"])

    context = navbar()
    context = context | email_confirm_check(request)

    # if login clicked
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login
            user = form.get_user()
            login(request, user)
            if urls["current_url"] == urls["previous_url"]:
                return redirect("catalog:home")
            else:
                return redirect(urls["previous_full_url"])
        else:
            if 'username' in form.data:
                user = User.objects.filter(username=form.data['username']).first()
                if user:
                    if not user.is_active:
                        context["check_email"] = True
    else:
        form = AuthenticationForm()

    context["form"] = form
    return render(request, 'accounts/login.html', context=context)


def LogoutView(request):
    urls = get_previous_and_current_url(request)
    if not request.user.is_authenticated:
        return redirect("accounts:login")
    if request.method == "POST":

accounts/templates/accounts/activation_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/cart.html
{% extends "layout.html" %}
{% load static %}
{% block content %}

    <div class="container" >
        <div style="max-width: 600px; margin: 50px auto">
            <h1 style="width: 45%; display: inline-block">Cart</h1>
            {% if messages %}
                {% for message in messages %}
                 <div class="my-5 alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}">
                    <h5 class="m-0">
                        {{ message }}
                    </h5>
                 </div>
                {% endfor %}
            {% endif %}
            {% if cart %}

                {% for pk, items in cart.items %}

                    <div style="margin-top: 30px; position: relative; width: 100%; border: 1px solid #eee;">



                    <a href="{{ items.object.get_absolute_url }}">
                   <div class="cart-item" style="position: relative; width: 100%; border: 1px solid #eee; padding: 15px; min-height: 70px">
                        <div style="display: inline-block; vertical-align: top; max-width: 40%">{{ forloop.counter }}. {{ items.object.title }}
                        </div>

                        <div style="max-width: 50px; display: inline-block">
                            <img src="{{ items.object.image.url }}">
                        </div>
                        <div style="position: absolute; right: 40px; bottom: 5px; margin-top: 10px; text-align: right   ">
                            Price Total: {{ items.price_total }}$<br>
                            One piece price: {{ items.object.price }}$
                        </div>

                        <form style="display: inline-block; position: absolute; right: 5px; top: 5px" method="post" action="{% url "accounts:cart-controller" %}">
                            {% csrf_token %}
                            <button class="login-button" style="padding: 0px 8px" value="{{ pk }}" type="submit" name="remove-from-cart">X</button>
                        </form>
                    </div>
</a>
                                        <div style="width: fit-content; margin: auto; padding: 10px">
                            <form method="post" action="{% url "accounts:cart-controller" %}">
                            {% csrf_token %}
                                {% if items.quantity > 1 %}
                            <button class="login-button" style="padding: 0px 8px" value="{{ pk }}" type="submit" name="cart-minus-one">-1</button>
                                {% endif %}
                                Quantity: {{items.quantity}}
                            {% if not items.max %}
                            <button class="login-button" style="padding: 0px 8px" value="{{ pk }}" type="submit" name="cart-plus-one">+1</button>
                            {% endif %}
                            </form>
                        </div>
                    </div>
                {% endfor %}
                            <h1 style="display: inline-block; float: left; margin-top: 16px">Total Price: {{ cart_total_price }}$</h1>
                <form method="post" action="{% url "accounts:checkout" %}" style="margin-top: 20px; margin-bottom: 100px; ">
                {% csrf_token %}
                <input type="submit" style="background: rgba(85,229,58,0.82); float: right; padding: 6px 40px" class="login-button" name="checkout" value="Buy">
                </form>
            {% else %}
                <h3 style="text-align: center">Your cart is empty</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/change_email_request_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to change your email,
http://{{ domain }}{% url 'accounts:change-email' uidb64=uid token=token %}

    If you did not make this request - ignore this message.
{% endautoescape %}

accounts/templates/accounts/login.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
    <div class="container" >
        <div style="max-width: 400px; margin: 50px auto">
        <h1>Login</h1>
        {% if email_confirm %}
            <div class="my-5 alert {% if email_confirm.success %}alert-success{% else %} alert-danger{% endif %}">
                    <h5 class="m-0">{{ email_confirm.message }}
            </h5>
                  </div>
        {% endif %}
        {% if messages %}
                {% for message in messages %}
                 <div class="my-5 alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}">
                    <h5 class="m-0">
                        {{ message }}
                    </h5>
                 </div>
                {% endfor %}
            {% endif %}
        {% if form.errors %}
            {% if check_email %}
                <div class="my-5 alert alert-warning">
                    <h5 class="m-0">Check Your email for activation link</h5>
                  </div>
            {% endif %}
                <div class="my-5 alert alert-danger">
                    <h5 class="m-0"><ul>{% for key, error in form.errors.items %}
                        <li>{{ error }}</li>
                    {% endfor %}</ul></h5>
                </div>

        {% endif %}

        <form action="{% url "accounts:login" %}" method="post">
            {% csrf_token %}
            <table>
            <tr>
                <td style="float:right">{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td style="float:right">{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
                <tr>
                <td></td>
                <td><input type="button" class="show-password" value="SHOW" onclick="myFunction()" id="show-hide"></td>
            </tr>
            <tr>
                <td></td>
                <td><input style="float:right" class="login-button" type="submit" value="login"></td>
            </tr>
            <tr>
                <td></td>
                <td><p style="float:right"><a href="{% url 'accounts:reset' %}">Lost password?</a></p></td>
            </tr>
            </table>

        </form>
        </div>
    </div>
    <script>
    function myFunction() {
  var x = document.getElementById("id_password");
  var y = document.getElementById("show-hide");
  if (x.type === "password") {
    x.type = "text";
    y.value = "HIDE"
  } else {
    x.type = "password";
    y.value = "SHOW"
  }


}
</script>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to reset your password,
http://{{ domain }}{% url 'accounts:reset-confirm' uidb64=uid token=token %}

    If you did not make this request - ignore this message.
{% endautoescape %}

accounts/templates/accounts/profile.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
    <div class="container" >
        <div style="max-width: 600px; margin: 50px auto">
            {% if delete_form %}
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Delete User Account</legend>
                        <p>Are you sure you want to delete your account?  This will permanently delete your
                           profile and any content you have generated.</p>
                </fieldset>
                <div class="form-group">
                    <input class="delete-submit " type="submit" name="delete-submit" value="Delete Account">
                        <button class="login-button" style="float:right;"
                           href="{% url 'accounts:profile' %}">Cancel</button>
                </div>
            </form>
            {% else %}
        <h1 style="display: inline-block">Profile</h1>
                {% if user_form %}
                    <input type="submit" onclick="window.location.href='{% url 'accounts:profile' %}';" value="Back" class="login-button"
                       style="display: inline-block; float: right">
                {% endif %}
        {% if email_confirm %}
            <div class="my-5 alert {% if email_confirm.success %}alert-success{% else %} alert-danger{% endif %}">
                    <h5 class="m-0">{{ email_confirm.message }}
            </h5>
                  </div>
        {% endif %}
            {% if messages %}
                {% for message in messages %}
                 <div class="my-5 alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}">
                    <h5 class="m-0">
                        {{ message }}
                    </h5>
                 </div>
                {% endfor %}
            {% endif %}

        {% if user_form.errors or profile_form.errors %}
        <div class="my-5 alert alert-danger">
            <h5 class="m-0">
                {% for key, error in user_form.errors.items %}
                {{ error }}
                {% endfor %}
                {% for key, error in profile_form.errors.items %}
                {{ error }}
                {% endfor %}
            </h5>
        </div>
        {% endif %}
        <table>
        <tr>
        <td style="vertical-align: top">
        <table style="margin-bottom: 30px">
            {% for key, value in profile.items %}
                <tr style="height:60px">
                <td style="font-weight: bold; width: 150px; text-align: right; padding-right: 20px">{{ key }}: </td>
                <td>{{ value }}</td>
                </tr>
            {% endfor %}
        {% if not user_form %}
            <tr>
                <td style="font-weight: bold; width: 150px; text-align: right; padding-right: 20px">Orders: </td>
                <td>
                    <input type="submit" onclick="window.location.href='{% url 'accounts:profile-orders' %}';" value="View" class="login-button">
                </td>
            </tr>
        {% endif %}
        </table>
        </td>
        <td></td>
        {% if user_form %}
            <td style="vertical-align: top">
            <form method="post">
            {% csrf_token %}
            <table>
                {% for field in user_form %}
                <tr>
                <td style="height: 60px">
                    {{ field }}
                </td>
                </tr>
                {% endfor %}
                {% for field in profile_form %}
                <tr>
                <td style="height: 60px">
                    {{ field }}
                </td>
                </tr>
            {% endfor %}
            </table>
            <input style="float: right" type="submit" name="edit-submit" value="Submit" class="login-button">
            </form>

            </td>
        {% endif %}
        </tr>
        {% if not user_form %}
            <tr>
                <td><form>{% csrf_token %}<input type="submit" class="login-button" name="change-password" value="Change password" formmethod="post" formaction="{% url 'accounts:password-change' %}"></form></td>
            <td><form>{% csrf_token %}<input type="submit" class="login-button" name="edit" value="Edit" formmethod="post"></form></td>
            </tr>
            <tr>
            <td></td>
            <td style="padding-top: 20px"><form>{% csrf_token %}<input type="submit" style="background: rgba(248,0,0,0.51)" class="login-button" name="delete" value="Delete Account" formmethod="post"></form></td>
            </tr>
        {% endif %}
        </table>
        {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "layout.html" %}

{% block content %}
        <div class="container" >
        <div style="max-width: 800px; margin: 50px auto">
        <h1 style="text-align: center">Sign Up</h1>
        {% if messages %}
            <div class="my-5 alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}">
                <h5 class="m-0">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </h5>
            </div>
        {% endif %}
        {% if user_form.errors or profile_form.errors %}
        <div class="my-5 alert alert-danger">
            <h5 class="m-0">
                {% for key, error in user_form.errors.items %}
                {{ error }}
                {% endfor %}
                {% for key, error in profile_form.errors.items %}
                {{ error }}
                {% endfor %}
            </h5>
        </div>
        {% endif %}
        <form action="{% url "accounts:signup" %}" method="post" style="margin: auto; width: fit-content">
        {% csrf_token %}
        <table>
            {% for field in user_form %}
                <tr>
                    <td style="float:right">{{ field.label_tag }}</td>
                    <td>{{ field }}</td>
                </tr>
                    {% if field.help_text %}
                        <tr><td style="float:right"><small style="display: none">{{ field.help_text }}</small></td></tr>

                    {% endif %}
                    {% if field.id_for_label == "id_password1" %}
                        <tr>
                        <td></td>
                        <td style="float: right; position: relative"><input style="position: absolute; top:6px" type="button" class="show-password" value="SHOW" onclick="myFunction()" id="show-hide"></td>
                        </tr>
                    {% endif %}
            {% endfor %}
            {% for field in profile_form %}
                {% if field.id_for_label == "id_agreement" %}
                    <tr><td style="text-align: center" colspan="2">Hereby I mutually agree with <a href="{% url "accounts:agreement" %}">Terms and conditions</a> {{ field}}</td></tr>
                {% elif field.id_for_label == "id_subscription" %}
                    <tr><td style="text-align: center" colspan="2">I want to receive newslatters {{ field}}</td></tr>
                {% else %}
                <tr>
                    <td style="float:right">{{ field.label_tag }}</td>
                    <td>{{ field }}</td>
                </tr>
                {% endif %}
                    {% if field.help_text %}
                        <tr><td style="float:right"><small style="display: none">{{ field.help_text }}</small></td></tr>

                    {% endif %}

            {% endfor %}

        <tr><td></td><td style="float:right"><input class="login-button" type="submit" value="Sign Up"></td></tr>

        </table>
        </form>
        </div>
        </div>
        <script>
    function myFunction() {
  var x1 = document.getElementById("id_password1");
  var x2 = document.getElementById("id_password2");
  var y = document.getElementById("show-hide");
  if (x1.type === "password") {
    x1.type = "text";
    x2.type = "text";
    y.value = "HIDE"
  } else {
    x1.type = "password";
    x2.type = "password";
    y.value = "SHOW"
  }


}
</script>
{% endblock %}

accounts/templates/accounts/subscribe_verification_email.html
{% autoescape off %}
Dear {{ user }},
Please click on the link to finish your email verification for subscription,
http://{{ domain }}{% url 'accounts:subscribe-verification' uidb64=uid token=token %}

    If you did not make this request - ignore this message.
{% endautoescape %}