Django_Online_Shop/urls.py
from django.contrib import admin
from django.urls import path
# library to add applications
from django.urls import include
# libraries to add static root for whole project
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

# adding primary application - home (index.html) and catalog
urlpatterns += [
    path('', include('catalog.urls'))
]

urlpatterns += [
    path('accounts/', include('accounts.urls'))
]

# adding media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("", views.AccountsRedirect, name="redirect"),
    path("agreement/", views.AgreementView, name="agreement"),
    path("profile/", views.ProfileView, name="profile"),
    path("profile/orders/", views.ProfileOrdersView, name="profile-orders"),
    path("profile/orders/<int:pk>", views.ProfileOrderDetailsView, name="profile-order-details"),
    path("signup/", views.SignUpView, name="signup"),
    path("activate/<slug:uidb64>/<slug:token>", views.activate, name='activate'),
    path("change-email/<slug:uidb64>/<slug:token>", views.change_email, name='change-email'),
    path("login/", views.LoginView, name="login"),
    path("logout/", views.LogoutView, name="logout"),
    path("password-reset/", views.PasswordReset, name="reset"),
    path("password-reset/<slug:uidb64>/<slug:token>", views.PasswordResetConfirm, name='reset-confirm'),
    path("password-change/", views.PasswordChangeView, name="password-change"),
    path("subscribe/", views.Subscribe, name="subscribe"),
    path("subscribe/<slug:uidb64>/<slug:token>", views.subscribe_verification, name='subscribe-verification'),
    path("cart/", views.CartView, name="cart"),
    path("cart/controller/", views.cart_controller, name="cart-controller"),
    path("cart/checkout/", views.CheckoutView, name="checkout"),
]

catalog/urls.py
from django.urls import path

import Django_Online_Shop.settings
from . import views
from . import models

app_name="catalog"

urlpatterns = [
    path('', views.IndexView.as_view(), name='home')
]

if Django_Online_Shop.settings.DEBUG:
    urlpatterns += [path("images/", views.image_transfer, name='images')]
#adding catalog urls
urlpatterns += [
    path("catalog/", views.CarsListView.as_view(), name="catalog")
]

urlpatterns += [
    path("catalog/search/", views.CarsSearchView.as_view(), name="search")
]


urlpatterns += [
    path("catalog/category/<slug:category>/", views.CarsByCategoryListView.as_view(), name="category")
]


urlpatterns += [
    path("car/<slug:slug>/", views.CarDetailView.as_view(), name="car")
]

urlpatterns += [
    path("rate/<int:pk>", views.rate, name="rate")
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.template.defaultfilters import slugify
import datetime
from cloudinary.models import CloudinaryField
from django.core.exceptions import ValidationError


# Create your models here.

# parent class - to capitilize name in Categories and Characteristics
# for the DRY purpose
class CapitilizingNames():
    def capitilize(self, name):
        words = name.split()
        i = 0
        for word in words:
            words[i] = word.capitalize()
            i += 1
        name = " ".join(words)
        return name

    @classmethod
    def get_classname(cls):
        return eval(cls.__name__)


class Categories(models.Model, CapitilizingNames):
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(blank=True, editable=False)

    def list_quantity(self):
        return Cars.objects.filter(category__name__exact=self.name).count()
    list_quantity.short_description = "Quantity in Category"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = CapitilizingNames.capitilize(self, self.name)
        if not self.slug:
            self.slug=slugify(self.name)
        super(Categories, self).save(*args, **kwargs)
        return super(self.get_classname(), self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Categories"
        verbose_name_plural = "Categories"


class Characteristics(models.Model, CapitilizingNames):
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(blank=True, editable=False)

    def __str__(self):
        return self.name

    def list_quantity(self):
        return Cars.objects.filter(characteristics__name__exact=self.name).count()
    list_quantity.short_description = "Quantity with Characteristic"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Characteristics, self).save(*args, **kwargs)
        self.name = CapitilizingNames.capitilize(self, self.name)
        return super(self.get_classname(), self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Characteristics"
        verbose_name_plural = "Characteristics"


class Cars(models.Model):
    title = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, blank=True, editable=False)
    characteristics = models.ManyToManyField(Characteristics, related_name='cars')
    category = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True)
    price = models.PositiveIntegerField(default=0, help_text='USD')
    #image = models.ImageField(upload_to='catalog/', blank=True, null=True)
    image = CloudinaryField(blank=True, null=True)
    description = models.TextField(max_length=1024, blank=True)
    quantity = models.PositiveIntegerField(default=0)
    CHOICES = (
        (1, "Bad"),
        (2, "Normal"),
        (3, "Good"),
        (4, "Very Good"),
        (5, "Excellent")
    )
    computed_rating = models.PositiveSmallIntegerField(choices=CHOICES, default=0)

    def __str__(self):
        return self.title

    def get_rating(self):
        from accounts.models import Rating
        from django.db.models import Sum
        ratings = Rating.objects.filter(car_id=self.id)
        rating = ratings.aggregate(Sum('rating'))
        if not rating['rating__sum']:
            rating = 0
        else:
            rating = rating['rating__sum']/ratings.count()
        return int(rating)
    get_rating.short_description = "Rating"

    def get_absolute_url(self):
        return reverse('catalog:car', args=[str(self.slug)])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.title)
        super(Cars, self).save(*args, **kwargs)

    def list_characteristics(self):
        return [char.name for char in self.characteristics.all()[:6]]
    list_characteristics.short_description = "Characteristics"

    class Meta:
        verbose_name = "Cars"
        verbose_name_plural = "Cars"

from django.db.models.signals import post_save
from django.dispatch import receiver
from accounts.models import Rating
@receiver(post_save, sender=Rating)
def update_computed_rating(sender, instance, **kwargs):
    instance.car.computed_rating = instance.car.get_rating()
    instance.car.save()

catalog/views.py
import datetime

import cloudinary.uploader
import requests
from django.shortcuts import render, redirect
import Django_Online_Shop.settings
from . import models
from . import forms
from .admin import get_all_fields
import random
from layout import models as LayoutModels
from django.views.generic.base import ContextMixin
from django.views import generic
from django.db.models import Q
from math import ceil
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

PAGINATE_BY_ITEMS_DEFAULT = 6


def get_previous_and_current_url(request):
    PROHIBITED_PREVIOUS_URLS = ['accounts']

    # get previous url
    previous_url = str(request.META.get('HTTP_REFERER'))

    # constructing like /catalog/jeep
    previous_url = previous_url[7:].strip('/').split("?")[0].rstrip("/").split('/')
    if len(previous_url) > 1:
        previous_url = "/" + "/".join(previous_url[1:])
    else:
        previous_url = "/"

    # constructing like /catalog/jeep
    current_url = str(request.path).split("?")[0].rstrip("/")

    # preparing for catalog views to clean up / keep filtering, page, pagination
    came_outside_catalog = False
    if current_url.strip("/").split("/")[0] == 'catalog':
        if previous_url.strip("/").split("/")[0] != 'catalog':
            came_outside_catalog = True
        else:
            if current_url != previous_url:
                came_outside_catalog = True
            else:
                came_outside_catalog = False

    # constructing full url with all params
    previous_full_url = previous_url
    if previous_full_url != "/":
        previous_page = str(request.session.get('previous_page', 1))
        previous_filters = request.session.get('filters', [])
        searched_list = request.session.get('searched_list', "")
        pag_by = request.session.get('pag_by', PAGINATE_BY_ITEMS_DEFAULT)
        previous_full_url += "/?page=" + previous_page + "&"
        for filter in previous_filters:
            previous_full_url += "characteristics=" + filter + "&"
        previous_full_url += "search=" + str(searched_list) + "&"
        previous_full_url += "Items_per_page=" + str(pag_by)

    # updating previous url is came not from /accounts app
    if previous_url != current_url and not previous_url.strip("/").split("/")[0] in PROHIBITED_PREVIOUS_URLS:
        request.session['previous_full_url'] = previous_full_url
        request.session['previous_url'] = previous_url
    else:
        if previous_url == "/accounts/cart":
            request.session['previous_full_url'] = previous_full_url
            request.session['previous_url'] = previous_url
        else:
            previous_url = request.session.get('previous_url', previous_url)
            previous_full_url = request.session.get('previous_full_url', previous_full_url)

    return {"previous_url": previous_url, "current_url": current_url, 'previous_full_url': previous_full_url,
            'came_outside_catalog': came_outside_catalog}


def get_searched_model(searched_list):
    searched_list = str(searched_list)
    q = Q()
    q |= Q(title__icontains=searched_list)
    q |= Q(category__name__icontains=searched_list)
    q |= Q(characteristics__name__icontains=searched_list)
    model = models.Cars.objects.filter(q).distinct()
    # if did not find any matches by whole search query, search by words
    if not model:
        q = Q()
        searched_list = searched_list.split(" ")
        for word in searched_list:
            q |= Q(title__icontains=word)
            q |= Q(category__name__icontains=word)
            q |= Q(characteristics__name__icontains=word)
        model = models.Cars.objects.filter(q).distinct()
    return model


# class for Navigation menu and footer
# to inherit in all views
class NavView(ContextMixin):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if Django_Online_Shop.settings.DEBUG == False:
            context["menu_list"] = LayoutModels.MenuList.objects.filter(is_active__exact=True).exclude(url__icontains="admin")
        else:
            context["menu_list"] = LayoutModels.MenuList.objects.filter(is_active__exact=True)
        # managing correct url prefix and suffix '/'
        for cont in context["menu_list"]:
            if len(cont.url) > 0:
                cont.url = "/" + cont.url.strip("/") + "/"
            else:
                cont.url = '/'

        # get footer
        context["footer"] = LayoutModels.Footer.objects.first()

        # get social links separate
        # to make east iteration, because stored in separate model
        if LayoutModels.SocialLinks.objects.exists():
            context["social_links"] = context["footer"].social_links.all()

        return context


# class for Pagination of Catalog
# to inherit in different views such as:
#   CarsListView
#   CarsByCategoryListView
# paginate_by shall be disabled within child class
# context["page_obj"] and context["paginator"] show wrong values
# on the next get_context_data()
# therefore are excluded from code, as well as paginate_by
# to avoid double pagination processing
class Pagination(ContextMixin):
    # defining model - inherited by child classes
    model = models.Cars

    def get_model(self):
        # getting model from child class
        class_name = self.__class__.__name__
        model = self.model
        # filtering model depending on view
        if class_name == "CarsSearchView":
            searched_list = self.request.GET.get('search')
            if searched_list:
                # if new search result
                searched_list = str(searched_list).strip(" ")
                self.request.session['searched_list'] = searched_list
                model = get_searched_model(searched_list)
            else:
                searched_list = self.request.session.get('searched_list', "")
                # if no new search result, get from memory
                # if memory empty - show all
                if searched_list:
                    model = get_searched_model(searched_list)
                else:
                    model = model.objects.all()
        elif class_name == "CarsListView":
            model = model.objects.all()
        else:
            model = model.objects.filter(category__slug__exact=self.kwargs['category'])

        model = model.order_by("-computed_rating", "-quantity", "pk")
        return model

    def get_context_data(self, *args, **kwargs):
        # standard - getting context
        context = super().get_context_data(*args, **kwargs)
        # if came not from same category clear all
        # later will be overriden by GET params if from accounts
        came_outside_catalog = get_previous_and_current_url(self.request)['came_outside_catalog']
        if came_outside_catalog == True:
            self.request.session['filters'] = []
            self.request.session['searched_list'] = ""
            self.request.session['previous_page'] = 1

        model = self.get_model()

        # send searched list to template
        context["searched_list"] = self.request.session.get('searched_list', "")

        # update if page is changed
        if 'page' in self.request.GET:
            self.request.session['previous_page'] = self.request.GET.get('page')

        # we keep previous page - because on form update current page is 1
        # so we remember what was the page before form change(items_per_page)
        page = int(self.request.session.get('previous_page', 1))

        # previous or standard value is taken for pagination
        # because we need to find out index of the first item BEFORE
        # the items_per_page was changed
        # if there is no previous value, perhaps user logged out
        # we check if GET sent for these reason
        pag_by = self.request.session.get('pag_by', None)
        if not pag_by:
            pag_by = self.request.GET.get('Items_per_page')
            if not pag_by:
                pag_by = PAGINATE_BY_ITEMS_DEFAULT
        pag_by = int(pag_by)
        # find out current page
        # by page and pagination before items_per_page was changed
        cars_list_index = (page - 1) * pag_by + 1

        # get dropdown menu value
        form = forms.ItemsPerPageForm(self.request.GET or None)
        if form.is_valid():
            self.request.session['pag_by'] = int(form.cleaned_data['Items_per_page'])
            # updating variable to find out new page with new pagination
            pag_by = int(form.cleaned_data['Items_per_page'])
        # On pages update, change page, whenever the dropdown box is not changed
        # put previous value
        else:
            form = forms.ItemsPerPageForm(initial={'Items_per_page': pag_by})

        # sending items_per_page form
        context["form"] = form

        # if clear all (filters) clicked we clear all filters
        # and go to first page if had filters
        if self.request.GET.get('filters-clear-all'):
            if self.request.session['filters']:
                cars_list_index = 1
                self.request.session['previous_page'] = 1
            self.request.session['filters'] = []

        # getting filters values
        main_filter_form = forms.MainFilter(self.request.GET or None)

        # only on submit filters
        if main_filter_form.is_valid():
            # save filter setup
            filters = main_filter_form.cleaned_data['characteristics']
            self.request.session['filters'] = filters
            # generate pagination - for filtered objects
            paginator = Paginator(model.filter(characteristics__name__in=filters), pag_by)
            # update values to send user to first page
            # on filters submission
            # if not from accounts
            if not self.request.GET.get('page'):
                cars_list_index = 1
                self.request.session['previous_page'] = 1
        else:
            if came_outside_catalog == True:

catalog/templates/car.html
{% extends "layout.html" %}
{% load static %}
{% load tags %}
{% block content %}
    <div class="container">


    <div class="car-content">

    {% if messages %}
    {% for message in messages %}
    <div class="my-5 alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}">
    <h5 class="m-0">
    {{ message }}
    </h5>
    </div>
    {% endfor %}
    {% endif %}

    <br>
    <a href="{{ go_back }}">Go back</a>
    <h1 style="text-align: center">{{ car.title }}   </h1>

    <div>
        {% if quantity > 0 %}
    <h2>Available: {{ quantity }} pcs</h2>
        {% else %}
    <h2>Not Available</h2>
        {% endif %}
    </div>
    <div style="float: right">
        <h2 >{{ car.price }} $</h2>
        {% if not in_cart %}
            {% if quantity > 0 %}
        <form method="post" action="{% url "accounts:cart-controller" %}">{% csrf_token %}<button type="submit" class="login-button" name="add-to-cart" value="{{ car.id }}">Add to cart</button></form>
            {% endif %}
        {% else %}
            <button type="button" class="login-button" onclick="location.href='{% url "accounts:cart" %}'">Already in Cart</button>
        {% endif %}
    </div>
        <a href="{% url 'catalog:category' category_url %}"><h2>{{ car.category }}</h2></a>
<form class="stars" method="post" action="{% url 'catalog:rate' car.pk %}">
{% csrf_token %}
{% for i in 5|xrange %}
<button name="btn" type="submit"
{% if car.get_rating >= i %}
class="fa fa-star"
{% else %}
class="fa fa-star-o"
{% endif %}
style="color: red; cursor: cell; background: none" value="{{ i }}"></button>
{% endfor %}
</form>
    {% if user.is_authenticated %}
        {% if rating %}
            <p>Your rating: {{ rating }}
        {% endif %}
    {% endif %}
    <div>
    <img style="align-content: center; max-width: 300px" src="{{car.image.url }}">
    </div>
    <h2>Characteristics:</h2>
    <p>
    {% for characteristic in characteristics %}
    {{ characteristic }}
    {% endfor %}
    </p>

        <br>

    <p>{{ car.description }}</p>
    <br>
        </div>
        </div>
{% endblock %}

catalog/templates/catalog.html
{% extends "layout.html" %}
{% load static %}
{% load tags %}
{% block additional_styles %}
    <link rel="stylesheet" href="{% static 'catalog/css/templatemo-sixteen.css' %}" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block content %}

    <div class="products">
      <div class="container">
        <div class="row">

            <!-- Start Filters -->
          <div class="col-md-12">
              <div class="filters-underline">
                  <div class="filters">
                    <div style="text-align: left">
                        <div class="dropdown">
                          <button class="dropbtn">Category</button>
                          <div class="dropdown-content">
                                    <a href="{% url 'catalog:catalog' %}"{% if request.path == '/catalog/'%} class="active"{% endif %} style="border-bottom: 1px solid #000000;">All</a>
                                {% for category in categories_list %}
                                    <a href="{% url 'catalog:category' category.slug %}" {% if request.path == category.url%} class="active"{% endif %}>{{ category.name }}</a>
                                {% endfor %}
                          </div>
                        </div>
                        <div style="display: inline-block; float: right">

                            <form action="{% url 'catalog:search' %}" method="get" style="display: table-caption">
                            <label style="display: inline; max-width: 49%">
                                <input type="search" name="search" style="max-width: 49%">
                                </label>
                                <button type="submit" class="filter-button">Search</button>
                        </form>

                        <!--
                            {% if searched_list %}
                                <div class="container">
                        <form method="get" action="{% url 'catalog:catalog' %}" style="display: inline-block;" >
                            <button type="submit" name="filters-clear-all" value="True" class="filter-button" style="right:0;margin-top: 10px; padding: 5px 10px; font-weight: 200; position: absolute; ">Clear searched</button>
                        </form>
                                </div>
                            {% endif %} -->
                        </div>




                    </div>
                    <div style="margin-top: 10px; display: inline-block">
                        <div style="text-align: center; font-size: 24px; font-weight: bold; color: black">
                            {{ catalog_title }}
                            {% if searched_list %}
                            <h6>Searched for: {{ searched_list }}</h6>
                            {% endif %}
                            <h6>Items found: {{ quantity }}</h6>
                            {% if messages %}
                            {% for message in messages %}
                            <div class="my-5 alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}">
                            <h5 class="m-0">
                            {{ message }}
                            </h5>
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <form style="margin-top: 20px; display:contents" method="get" >
                        <ul id="{{ main_filter_form.characteristics.auto_id }}">
                            {% for filter in main_filter_form.characteristics %}
                                {% if filter.choice_label in active_filters %}
                                <li {% if filter.choice_label in main_filter_form.characteristics.value %}class="active"{% endif %}>
                                {{ filter }}
                                </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                            <button type="submit" value="filter" class="filter-button">Filter</button>

                        </form>
                        <form method="get" style="display: inline-block;" >
                            <button type="submit" name="filters-clear-all" value="True" class="filter-button" style="margin-top: 10px; padding: 5px 10px; font-weight: 200; position: absolute; left: 0;">Clear all</button>
                        </form>

                        <form action="" method="get" style="display: inline-block;">
                        <div class="form-dropdown">
                        <label  for="{{ form.Items_per_page.name }}">{{ form.Items_per_page.label }}</label>
                        {% for field in form %}
                            {{ field }}
                        {% endfor %}
                        </div>
                        </form>
                    </div>
                  </div>
              </div>
          </div>
            <!-- End Filters -->
            <!-- Start Content -->
          <div class="col-md-12">
            <div class="filters-content">
                <div class="row grid" style="position: relative;">
                    <!-- Start Item -->
                    {% if cars_list %}
                        {% for car in cars_list.object_list %}
                    <div class="col-lg-4 col-md-4 all dev" >
                      <div class="product-item" style="position: relative">
                          <a href="{{ car.get_absolute_url }}">
                              <div style="width: 100%; height: 100%; {% if car.quantity == 0 %}background: rgba(236,236,236,0.43);{% endif %} z-index: 1; position: absolute;">
                                  {% if car.quantity == 0 %}<p class="not-available">Not available</p>{% endif %}
                              </div>
                          </a>
                        <img src="{{car.image.url }}" alt="" >
                        <div class="down-content" style="margin-bottom: 50px">
                          <h4 style="max-width: 180px; height: 62px; margin-bottom: 12px">{{ car.title }}</h4>
                          <h6>{{ car.price }}$</h6>
                          <p>{{ car.description }}</p>
                        </div>
                        <form class="stars" method="post" style="position: absolute; z-index: 1; bottom: 10px; left: 30px" action="{% url 'catalog:rate' car.pk %}">
                                {% csrf_token %}
                                {% for i in 5|xrange %}
                                    <button name="btn" type="submit"
                                    {% if car.computed_rating >= i %}
                                            class="fa fa-star"
                                            {% else %}
                                            class="fa fa-star-o"
                                    {% endif %}
                                            style="color: red; cursor: cell; background: none" value="{{ i }}"></button>
                                {% endfor %}
                            </form>
                      </div>
                    </div>
                    {% endfor %}
                    {% else %}
                        <h1 style="margin: auto">There are no such cars in the catalog for the moment =(((</h1>
                    {% endif %}
                    <!-- End Items -->
                </div>
            </div>
          </div>
            <!-- End Contents -->
            <!-- Start Pages/Paginator -->
          <div class="col-md-12 paginator-bottom">
            <ul class="pages">

                {% if pages_middle_left != None %}

                    <li><a href="?page={{ 1 }}">1</a></li>
                        {% if pages_middle_left != 1 %}
                            <li><a href="?page={{ pages_middle_left }}">...</a></li>
                        {% endif %}
                {% endif %}
                {% for page in pages_list %}
                    <li {% if cars_list.number == page %}class="active"{% endif %}><a
                            href="?page={{ page }}">{{ page }}</a></li>
                {% endfor %}
                {% if pages_middle_right != None %}
                    {% if pages_middle_right != ars_list.paginator.num_pages %}
                        <li><a href="?page={{ pages_middle_right }}">...</a></li>
                    {% endif %}
                    <li><a href="?page={{ cars_list.paginator.num_pages }}">{{ cars_list.paginator.num_pages }}</a></li>
                {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- End Pages/Paginator -->
{% endblock %}

catalog/templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
Autoy Shop - Home Page
{% endblock %}
{% block content %}
<section class="slider_section">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container-fluid padding_dd">
              <div class="carousel-caption">
                <div class="row">
                  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                    <div class="text-bg">
                     <span>Welcome To Autoy Shop</span>
                      <h1>All Car Toys is here</h1>
			{% if random_model %}	
                        <a  href="{{ random_model.get_absolute_url }}">
                            <p style="float: left"> {{ random_model.title }}</p> <p style="text-align: end"> {{ random_model.price }}   $</p></a>
                        <p style="color: rgb(108,108,108); font-style: italic; max-height: 300px; overflow: hidden"> {{ random_model.description }}</p>
			{% endif %}
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
		    {% if random_model %}
                    <div class="images_box" >
                      <figure><a href="{{ random_model.get_absolute_url }}"><img  src="{{random_model.image.url}}"></a></figure>
                    </div>
		    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div>
</header>


<!-- contact -->
<div id="contact" class="contact" style="background-image: url({% get_media_prefix %}/catalog/porsche-911-Carrera-4S-Pullback_-lava-orange-1-43_2048x.jpg);)">
  <div class="container">
   <div class="row">
     <div class="col-md-12">
                <div class="titlepage">
                  <h2>Find <strong class="llow">us</strong></h2>
                </div>
   </div>

</div>
    <div class="white_color">
      <div class="row">

        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12" style="flex: 0 0 100%; max-width: 100%">
<div id="map">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52346.38311463434!2d30.71658353398402!3d46.40671850771397!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40c6338abced7f1b%3A0x805f1ecf623d596d!2z0JDQstGC0L7QstC40LrRg9C_IEFydEF1dG8g0LIg0J7QtNC10YHRlg!5e0!3m2!1sen!2sua!4v1635513590259!5m2!1sen!2sua" width="100%" height="100%" style="border:0; padding: 20px;" allowfullscreen="" loading="lazy"></iframe>
          </div>
           </div>
          </div>
        </div>

      </div>
    </div>
</div>
</div>
    <!-- end contact -->
{% endblock %}