Django_Online_Shop/urls.py
from django.contrib import admin
from django.urls import path
# library to add applications
from django.urls import include
# libraries to add static root for whole project
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

# adding primary application - home (index.html) and catalog
urlpatterns += [
    path('', include('catalog.urls'))
]

urlpatterns += [
    path('accounts/', include('accounts.urls'))
]

# adding media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("", views.AccountsRedirect, name="redirect"),
    path("agreement/", views.AgreementView, name="agreement"),
    path("profile/", views.ProfileView, name="profile"),
    path("profile/orders/", views.ProfileOrdersView, name="profile-orders"),
    path("profile/orders/<int:pk>", views.ProfileOrderDetailsView, name="profile-order-details"),
    path("signup/", views.SignUpView, name="signup"),
    path("activate/<slug:uidb64>/<slug:token>", views.activate, name='activate'),
    path("change-email/<slug:uidb64>/<slug:token>", views.change_email, name='change-email'),
    path("login/", views.LoginView, name="login"),
    path("logout/", views.LogoutView, name="logout"),
    path("password-reset/", views.PasswordReset, name="reset"),
    path("password-reset/<slug:uidb64>/<slug:token>", views.PasswordResetConfirm, name='reset-confirm'),
    path("password-change/", views.PasswordChangeView, name="password-change"),
    path("subscribe/", views.Subscribe, name="subscribe"),
    path("subscribe/<slug:uidb64>/<slug:token>", views.subscribe_verification, name='subscribe-verification'),
    path("cart/", views.CartView, name="cart"),
    path("cart/controller/", views.cart_controller, name="cart-controller"),
    path("cart/checkout/", views.CheckoutView, name="checkout"),
]

catalog/urls.py
from django.urls import path

import Django_Online_Shop.settings
from . import views
from . import models

app_name="catalog"

urlpatterns = [
    path('', views.IndexView.as_view(), name='home')
]

if Django_Online_Shop.settings.DEBUG:
    urlpatterns += [path("images/", views.image_transfer, name='images')]
#adding catalog urls
urlpatterns += [
    path("catalog/", views.CarsListView.as_view(), name="catalog")
]

urlpatterns += [
    path("catalog/search/", views.CarsSearchView.as_view(), name="search")
]


urlpatterns += [
    path("catalog/category/<slug:category>/", views.CarsByCategoryListView.as_view(), name="category")
]


urlpatterns += [
    path("car/<slug:slug>/", views.CarDetailView.as_view(), name="car")
]

urlpatterns += [
    path("rate/<int:pk>", views.rate, name="rate")
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.template.defaultfilters import slugify
import datetime
from cloudinary.models import CloudinaryField
from django.core.exceptions import ValidationError


# Create your models here.

# parent class - to capitilize name in Categories and Characteristics
# for the DRY purpose
class CapitilizingNames():
    def capitilize(self, name):
        words = name.split()
        i = 0
        for word in words:
            words[i] = word.capitalize()
            i += 1
        name = " ".join(words)
        return name

    @classmethod
    def get_classname(cls):
        return eval(cls.__name__)


class Categories(models.Model, CapitilizingNames):
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(blank=True, editable=False)

    def list_quantity(self):
        return Cars.objects.filter(category__name__exact=self.name).count()
    list_quantity.short_description = "Quantity in Category"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = CapitilizingNames.capitilize(self, self.name)
        if not self.slug:
            self.slug=slugify(self.name)
        super(Categories, self).save(*args, **kwargs)
        return super(self.get_classname(), self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Categories"
        verbose_name_plural = "Categories"


class Characteristics(models.Model, CapitilizingNames):
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(blank=True, editable=False)

    def __str__(self):
        return self.name

    def list_quantity(self):
        return Cars.objects.filter(characteristics__name__exact=self.name).count()
    list_quantity.short_description = "Quantity with Characteristic"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Characteristics, self).save(*args, **kwargs)
        self.name = CapitilizingNames.capitilize(self, self.name)
        return super(self.get_classname(), self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Characteristics"
        verbose_name_plural = "Characteristics"


class Cars(models.Model):
    title = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, blank=True, editable=False)
    characteristics = models.ManyToManyField(Characteristics, related_name='cars')
    category = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True)
    price = models.PositiveIntegerField(default=0, help_text='USD')
    #image = models.ImageField(upload_to='catalog/', blank=True, null=True)
    image = CloudinaryField(blank=True, null=True)
    description = models.TextField(max_length=1024, blank=True)
    quantity = models.PositiveIntegerField(default=0)
    CHOICES = (
        (1, "Bad"),
        (2, "Normal"),
        (3, "Good"),
        (4, "Very Good"),
        (5, "Excellent")
    )
    computed_rating = models.PositiveSmallIntegerField(choices=CHOICES, default=0)

    def __str__(self):
        return self.title

    def get_rating(self):
        from accounts.models import Rating
        from django.db.models import Sum
        ratings = Rating.objects.filter(car_id=self.id)
        rating = ratings.aggregate(Sum('rating'))
        if not rating['rating__sum']:
            rating = 0
        else:
            rating = rating['rating__sum']/ratings.count()
        return int(rating)
    get_rating.short_description = "Rating"

    def get_absolute_url(self):
        return reverse('catalog:car', args=[str(self.slug)])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.title)
        super(Cars, self).save(*args, **kwargs)

    def list_characteristics(self):
        return [char.name for char in self.characteristics.all()[:6]]
    list_characteristics.short_description = "Characteristics"

    class Meta:
        verbose_name = "Cars"
        verbose_name_plural = "Cars"

from django.db.models.signals import post_save
from django.dispatch import receiver
from accounts.models import Rating
@receiver(post_save, sender=Rating)
def update_computed_rating(sender, instance, **kwargs):
    instance.car.computed_rating = instance.car.get_rating()
    instance.car.save()

layout/models.py
from django.db import models

# Create your models here.

class MenuList(models.Model):
    name = models.CharField(max_length=32, help_text='Menu name')

    url = models.CharField(max_length=32, blank=True, default="")

    is_active = models.BooleanField(default=True)

    order_num = models.PositiveSmallIntegerField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Menu list"
        verbose_name_plural = "Menu list"
        ordering = ['order_num']

class SocialLinks(models.Model):
    name = models.CharField(max_length=64, unique=True)
    url = models.URLField()
    order_num = models.PositiveSmallIntegerField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Social Links"
        verbose_name_plural = "Social Links"
        ordering = ['order_num']


class Footer(models.Model):
    name = models.CharField(max_length=24, default="Footer")
    address_show = models.BooleanField(default=True)
    address = models.CharField(max_length=512)
    address_google_maps_dir_url = models.URLField(blank=True, default="", help_text="URL for directions from Google Maps, leave empty to disable")
    phone = models.CharField(max_length=24)
    e_mail = models.CharField(max_length=64)
    social_links_show = models.BooleanField(default=True)
    social_links = models.ManyToManyField(SocialLinks, related_name='social_links')
    newsletter_show = models.BooleanField(default=True)
    copyright_show = models.BooleanField(default=True)
    copyright_text = models.CharField(max_length=128)


    def save(self, *args, **kwargs):
        if not self.pk and Footer.objects.exists():
        # if you'll not check for self.pk
        # then error will also raised in update of exists model
            raise ValidationError('There is can be only one Footer instance')
        return super(Footer, self).save(*args, **kwargs)

    def list_social_links(self):
        return [link.name for link in self.social_links.all()]
    list_social_links.short_description = "Social Links"

    def __str__(self):
        return 'Footer'

    class Meta:
        verbose_name = "Footer"
        verbose_name_plural = "Footer"

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <!-- The website is developed by Vladyslav Zolotukhin, 2021 -->
   <!-- The Free template SHREE FREE CSS TEMPLATE is copied from -->
   <!-- https://www.free-css.com/free-css-templates/page265/shree -->
<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>{% block title %}Autoy Shop{% endblock %}</title>
  <meta name="keywords" content="toy, auto, automobile, shop, online, store, ukraine, odessa, odesa">
  <meta name="description" content="Buy toy autos">
  <meta name="author" content="Vladyslav Zolotukhin">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'icon/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    {% block additional_styles %}
    {% endblock %}
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">

  {% block header %}
  <!-- header -->
  <header>
    <!-- header inner -->
    <div class="header-top">
      <div class="header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                  <div class="logo">
                    <a href="{% url 'catalog:home' %}"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">

               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                        {% for menu in menu_list %}
                                <li {% if request.path == menu.url %} class="active"{% elif  menu.name == 'Catalog' %}
                                                                      {% if request.path == car_detail_path %}
                                                                      class="active"
                                                                      {% elif request.path == '/catalog/search/' %}

                                                                            class="active"
                                                                          {% else %}
                                                                              {% for category in categories_list %}
                                                                          {% if request.path == category.url %}
                                                                              class="active"
                                                                          {% endif %}
                                                                              {% endfor %}
                                                                      {% endif %}


                                {% endif %}> <a href='{{ menu.url }}'>{{ menu.name }}</a></li>

                        {% endfor %}

                        <li><a  href="{% url 'accounts:profile' %}" style="position: relative; {% if not user.is_authenticated %}left: 5px;{% endif %}"><img class="login-button-navbar" style="border-radius: 100% ;padding:0; max-width: 40px; max-height: 40px;" {% if request.path == "/accounts/profile/" %}
                                        src="{% static 'icon/profile_icon_active.png' %}"
                                        {% else %}src="{% static 'icon/profile_icon.png' %}"{% endif %} alt="Guest/User Profile" /></a>
                            {% if not user.is_authenticated %}
                                <form method="get">
                                    <input class="login-button-navbar" type="submit" formaction="{% url 'accounts:signup' %}" value="Sign Up"
                                    {% if request.path == "/accounts/signup/" %}
                                        style="color: #044997"
                                        {% endif %}>
                                    |
                                    <input class="login-button-navbar" type="submit" formaction="{% url 'accounts:login' %}" value="Login"
                                    {% if request.path == "/accounts/login/" %}
                                        style="color: #044997"
                                        {% endif %}>
                                </form>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <form action="{% url 'accounts:logout' %}" method="post">{% csrf_token %}<button class="login-button-navbar" type="submit">Logout</button></form>
                            {% endif %}
                        </li>
                        <li><a href="{% url "accounts:cart" %}"><img class="login-button-navbar" style="max-width: 60px; max-height: 60px; padding: 0; border-radius: 100%" {% if request.path == "/accounts/cart/" %}
                                        src="{% static 'icon/cart_icon_active.png' %}"
                                        {% else %}src="{% static 'icon/cart_icon.png' %}"{% endif %} alt="Shopping Cart" /></a></li>
                     </ul>
                   </nav>
                 </div>
               </div>
              </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->
           <!-- end header -->
  {% endblock %}

{% block content %}

{% endblock %}
    <!--  footer -->
    <footr>
      <div class="footer ">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
             <a href="{% url 'catalog:home' %}" class="logo_footer"> <img src="{% static 'images/logo2.png' %}" alt="#"/></a>
            </div>
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 ">
              <div class="row">
              {% if footer.social_links_show == True %}
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 ">
                  <div class="address">
                    <h3>Address </h3>
                    <ul class="loca">
                      <li>
                          {% if footer.address_google_maps_dir_url != "" %}
                        <a href="{{ footer.address_google_maps_dir_url }}">{{ footer.address }}</a>
                              {% else %}
                        {{ footer.address }}
                              {% endif %}</li>
                        <li>
                          <a href="tel:{{ footer.phone }}">{{ footer.phone }}</a></li>
                          <li>
                            <a href="mailto:{{ footer.e_mail }}">{{ footer.e_mail }}</a></li>
                          </ul>
                        </div>
                      </div>
              {% endif %}
                      {% if footer.social_links_show == True %}
                      <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="address">
                          <h3>Social Links</h3>
                          <ul class="Menu_footer">
                              {% for sl in social_links  %}
                            <li><a href="{{ sl.url }}">{{ sl.name }}</a></li>
                              {% endfor %}
                          </ul>
                        </div>
                      </div>
                      {% endif %}
                      {% if footer.newsletter_show == True %}
                      <div class="col-lg-4 col-md-6 col-sm-6 ">
                        <div class="address">
                          <h3>Newsletter</h3>
                           <form class="news" action="{% url 'accounts:subscribe' %}" method="post">
                               {% csrf_token %}
                           <input class="newslatter" placeholder="Enter your email" type="text" name="email">
                            <button class="submit">Subscribe</button>
                            </form>
                        </div>
                      </div>
                      {% endif %}
                    </div>
                  </div>

                </div>
              </div>
              {% if footer.copyright_show == True %}
              <div class="copyright">
                <div class="container">
                  <p>{{ footer.copyright_text }}</p>
                </div>
              </div>
              {% endif %}
            </div>

          </footr>
          <!-- end footer -->
          <!-- Javascript files-->





</body>

</html>